travis:
  secure:
    BINSTAR_TOKEN: hsQoCV8nMnrApB79ayFgoH2J/6qHe06B2Jd+Hiav2DnztyCYz7Fo5lUXyFNdZW91yr51Gl6UikxTIRvGXOABbhjku1JJa+/2K50l02e95eS24Di6fJb61VuEcTj281WzauB4iuwDk02cBo52oKYKGxWbO/dvGmlRznMVeFBiosP0LumlgCDL/qvMZJzm7sQnG0ns2hvQvJb0Ed1MknRXaHyaN2980Po9dynJ2vqPtal1kZq3qPb9CSNBbRkm4846TTqnFMhaRGirDeXMTcVH/KCUdrgclFgitXbCi2cCpMzN+1QLdDJVqgAhwx7M8MRKABwO1KX0yQwXaX7PzULHIhSSXjgtH1+5enIgRj6V6QEJOD1UYZFoET7j5FzyzJHh5OnA+Qz5ZOZkuAhbeuB7BrSQTBwqsWhyyZ2OvMYxPGVEX7huDRv0R39g+7QnHbYZACEuBiKmHtQKRgiIqkPYni8P+nuy9tcb15cN2hNeSNvaMyfCS2LGbRV8zi+k7tMfDOrPuhmC/l/+OYSWxkfGrs6XxaMvtnSgzkPeRzs2FpbH3mfcEfVzE5UhH5M1dKnTzLJJH1cL2KVcuCCnvmmaKDAyLGB+YY/rw8eaQodpRRuwvBX9a7sfE6SOOZHdYJPYiSWWzWWG/OElTO+C4RhHVESI/Tp9eAWfIiqOl3tk8J8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
